apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoewebsite
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shoewebsite
  template:
    metadata:
      labels:
        app: shoewebsite
    spec:
      containers:
      - name: shoewebsite
        image: saikishorea/shoewebsite:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shoewebsite-service
  namespace: ecommerce
spec:
  selector:
    app: shoewebsite
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
